package Setup; # to make podweaver happy

# VERSION

1;
# ABSTRACT: Specification for setup module

=head1 SPECIFICATION VERSION

1.0

=head1 SPECIFICATION

This is a specification for setup modules. Setup modules are normal Perl modules
that live under the C<Setup::> namespace and contain setup functions. Setup
functions are normal Perl subroutines, typically named with C<setup_> prefix
(like C<setup_file>, C<setup_unix_user>, etc.) They are typically used for,
well, setting up stuffs, like software installation, system setup, or
configuration management.

Setup functions MUST have metadata, as specified in L<Rinci> specification.

Setup functions MUST support transactions, as described in
L<Rinci::Transaction>.

Since setup functions might be used in unsetup (uninstallation) of software
months or even years after setup (installation), their interface should be
stable. During setup, undo actions are recorded in transaction database and
might be used years later.

=cut
