package Setup; # to make podweaver happy

# VERSION

1;
# ABSTRACT: Specification for setup module

=head1 SPECIFICATION VERSION

1.0

=head1 SPECIFICATION

This is a specification for setup modules. Setup modules are normal Perl modules
that live under the C<Setup::> namespace and contain setup functions. Setup
functions are normal Perl subroutines, typically named with C<setup_> prefix
(like C<setup_file>, C<setup_unix_user>, etc.) They are typically used for,
well, setting up stuffs, like software installation, system setup, or
configuration management.

Setup functions must have metadata, as specified in L<Rinci> specification.

Setup functions must support transactions, as described in
L<Rinci::function::Transaction>.

Setup functions should also be written with the helper module
L<Perinci::Sub::Gen::Undoable>, to make all Setup functions more consistent.

Aside from idempotency, setup functions must also check for acceptable initial
condition. There could be various state changes between the time of do and undo
action; a file can be deleted or modified by other processes. The undo action
must be flexible enough so it can reverse whatever state changes the previous do
phase did whenever it can, but not disrupt other processes' changes.

=cut
